### PR TITLE
Add User Authentication and migrate model

### PR DESCRIPTION
**Pull request by Markchau**
Modify the model definition
makemigrations and migrate
Add User authentication --> Admin could add User directly in Django Admin & all User could use the application after login if credentials are authenticated, User could logout
Add new template files, views and urls

### CODE REVIEW

**Comment by tommycmc** [comment]
`raise ValueError('Related model %r cannot be resolved' % self.remote_field.model)
ValueError: Related model 'locations.staffuser' cannot be resolved`

Why this error appears when calling "py manage.py migrate" but not "py manage.py migrate location"? 
I think one reason is not linking app correctly. You can change "locations.apps.LocationsConfig" to "locations". Also, delete all migration file, e.g. _0001_initial.py_, ..., but except __init__py_. Make migration from clean state. Here is the indication image and successful migration using your codes.

iter2_setting

iter2_concole_after_setting

**Comment by tommycmc** [comment]
Also, I notice that when we extends AbstractUser in StaffUser, it automatically generate fields in  ordinary User model, e.g. username, password, id, is_superuser. Here is the model file, and the corresponding migration file, e.g. _000X_YYYYY.py_ in migrations, and mark ordinary fields in red arrow and customized fields in yellow arrow

iter2_models_before

iter2_models_migrate_before
 
 
 

If we comment the custom field, _userName_ that replaces the field that comes from ordinary User model, _username_. Then, I make migration. Here is the modified model and migration file images. Yellow arrows show the uncommenting. 

iter2_models_after

iter2_models_migrate_after

It is better to not add fields in custom model that exist in ordinary User model, that is username, password, id. Otherwise, it makes conflict issues possibly.

**Comment by Markchau** [comment]
I comment out all the custom field in StaffUser except the chpStaffNumber

**Comment by tommycmc** [comment]
If we also change 'location' parameter in INSTALLED APP correctly, we can run normal migration command correctly

**Pull request merged**
